version: '3.7'

services:
  nls-demo:
    image: b051/nls-demo
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    command: tail -f /dev/null
    environment:
      PULSE_SERVER: docker.for.mac.host.internal
      ENV_YML: /root/env.yml
    working_dir: /runtime
    volumes:
      - type: bind
        source: ${HOME}/.config/pulse
        target: /root/.config/pulse
      - ../src:/runtime/src
      - ../.git:/runtime/.git
      - ../demo:/runtime/demo
      - ../.gitignore:/runtime/.gitignore
      - ../package.json:/runtime/package.json
      - ../.npmrc:/runtime/.npmrc
      - ../tsconfig.json:/runtime/tsconfig.json
      - ../README.md:/runtime/README.md
      - ../.devcontainer:/runtime/.devcontainer
      - ${HOME}/env.yml:/root/env.yml